In [47]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [48]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [49]:
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [50]:
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [51]:
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [52]:
one_hot_encoder_geo=OneHotEncoder()
geo_encoded=one_hot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=one_hot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [53]:
data=pd.concat([data.drop(['Geography'], axis=1), geo_encoded_df], axis=1)
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [54]:
x=data.drop(['EstimatedSalary'],axis=1)
y=data['EstimatedSalary']

In [55]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [56]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [57]:
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(one_hot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [58]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [60]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1)
])

WARNING:tensorflow:From c:\Users\HP\OneDrive\Desktop\artificialnn\.venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [61]:
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])
model.summary()

WARNING:tensorflow:From c:\Users\HP\OneDrive\Desktop\artificialnn\.venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [63]:
from tensorflow.keras.callbacks import EarlyStopping , TensorBoard
import datetime

In [74]:
log_dir="regressionlogs/fit/" +datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [75]:
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [76]:
history = model.fit(
    x_train, y_train,
    validation_data=(x_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\HP\OneDrive\Desktop\artificialnn\.venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\HP\OneDrive\Desktop\artificialnn\.venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 3s 6ms/step - loss: 100384.9219 - mae: 100384.9219 - val_loss: 98543.6250 - val_mae: 98543.6250
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 99727.3672 - mae: 99727.3672 - val_loss: 97218.2969 - val_mae: 97218.2969
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 97399.5234 - mae: 97399.5234 - val_loss: 93753.7266 - val_mae: 93753.7266
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 92646.7734 - mae: 92646.7734 - val_loss: 87772.4922 - val_mae: 87772.4922
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 85559.0078 - mae: 85559.0078 - val_loss: 79926.7500 - val_mae: 79926.7500
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 77046.7109 - mae: 77046.7109 - val_loss: 71471.0938 - val_mae: 71471.0938
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 68504.3594 - mae: 68504.3594 - val_loss: 63724.9492 - val_mae: 63724.9492
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 61189.2227 - mae: 61189.2227 - val_loss: 57705.8828 - val_mae: 57705.8828
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 56022.8750 - mae: 56022.8750 - val_loss: 53925.1445 - val_mae: 53925.1445
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 52994.1523 - mae: 52994.1523 - val_loss: 51995.3711 - val_mae: 51995.3711
Epoch 11/100
250/250 [==============================] - 1s 4ms/step - loss: 51449.3906 - mae: 51449.3906 - val_loss: 51239.0781 - val_mae: 51239.0781
Epoch 12/100
250/250 [==============================] - 1s 4ms/step - loss: 50837.2617 - mae: 50837.2617 - val_loss: 51010.7188 - val_mae: 51010.7188
Epoch 13/100
250/250 [==============================] - 1s 4ms/step - loss: 50585.6484 - mae: 50585.6484 - val_loss: 50902.8672 - val_mae: 50902.8672
Epoch 14/100
250/250 [==============================] - 1s 4ms/step - loss: 50467.8164 - mae: 50467.8164 - val_loss: 50829.0508 - val_mae: 50829.0508
Epoch 15/100
250/250 [==============================] - 1s 4ms/step - loss: 50386.7383 - mae: 50386.7383 - val_loss: 50766.9375 - val_mae: 50766.9375
Epoch 16/100
250/250 [==============================] - 1s 4ms/step - loss: 50321.3594 - mae: 50321.3594 - val_loss: 50712.5000 - val_mae: 50712.5000
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 50266.1289 - mae: 50266.1289 - val_loss: 50663.6562 - val_mae: 50663.6562
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 50217.5742 - mae: 50217.5742 - val_loss: 50625.1211 - val_mae: 50625.1211
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 50166.7656 - mae: 50166.7656 - val_loss: 50585.0469 - val_mae: 50585.0469
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 50121.4531 - mae: 50121.4531 - val_loss: 50553.6953 - val_mae: 50553.6953
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 50085.7773 - mae: 50085.7773 - val_loss: 50518.4336 - val_mae: 50518.4336
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 50048.4492 - mae: 50048.4492 - val_loss: 50492.0977 - val_mae: 50492.0977
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 50017.1367 - mae: 50017.1367 - val_loss: 50462.9570 - val_mae: 50462.9570
Epoch 24/100
250/250 [==============================] - 1s 4ms/step - loss: 49983.9375 - mae: 49983.9375 - val_loss: 50444.7773 - val_mae: 50444.7773
Epoch 25/100
250/250 [==============================] - 1s 4ms/step - loss: 49952.7148 - mae: 49952.7148 - val_loss: 50424.2188 - val_mae: 50424.2188
Epoch 26/100
250/250 [==============================] - 1s 4ms/step - loss: 49927.6289 - mae: 49927.6289 - val_loss: 50411.2734 - val_mae: 50411.2734
Epoch 27/100
250/250 [==============================] - 1s 4ms/step - loss: 49897.4453 - mae: 49897.4453 - val_loss: 50389.8398 - val_mae: 50389.8398
Epoch 28/100
250/250 [==============================] - 1s 4ms/step - loss: 49874.3711 - mae: 49874.3711 - val_loss: 50366.6328 - val_mae: 50366.6328
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 49849.2773 - mae: 49849.2773 - val_loss: 50350.5625 - val_mae: 50350.5625
Epoch 30/100
250/250 [==============================] - 1s 3ms/step - loss: 49829.4844 - mae: 49829.4844 - val_loss: 50341.9453 - val_mae: 50341.9453
Epoch 31/100
250/250 [==============================] - 1s 3ms/step - loss: 49809.4414 - mae: 49809.4414 - val_loss: 50329.5039 - val_mae: 50329.5039
Epoch 32/100
250/250 [==============================] - 1s 3ms/step - loss: 49785.8320 - mae: 49785.8320 - val_loss: 50322.6602 - val_mae: 50322.6602
Epoch 33/100
250/250 [==============================] - 1s 4ms/step - loss: 49769.0938 - mae: 49769.0938 - val_loss: 50316.8984 - val_mae: 50316.8984
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 49748.9531 - mae: 49748.9531 - val_loss: 50308.9492 - val_mae: 50308.9492
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 49733.3750 - mae: 49733.3750 - val_loss: 50306.5625 - val_mae: 50306.5625
Epoch 36/100
250/250 [==============================] - 1s 4ms/step - loss: 49713.1562 - mae: 49713.1562 - val_loss: 50289.7461 - val_mae: 50289.7461
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 49701.1250 - mae: 49701.1250 - val_loss: 50288.4336 - val_mae: 50288.4336
Epoch 38/100
250/250 [==============================] - 1s 3ms/step - loss: 49686.7461 - mae: 49686.7461 - val_loss: 50281.4688 - val_mae: 50281.4688
Epoch 39/100
250/250 [==============================] - 1s 3ms/step - loss: 49672.0234 - mae: 49672.0234 - val_loss: 50279.4141 - val_mae: 50279.4141
Epoch 40/100
250/250 [==============================] - 1s 3ms/step - loss: 49657.8203 - mae: 49657.8203 - val_loss: 50274.9844 - val_mae: 50274.9844
Epoch 41/100
250/250 [==============================] - 1s 3ms/step - loss: 49645.1328 - mae: 49645.1328 - val_loss: 50272.8086 - val_mae: 50272.8086
Epoch 42/100
250/250 [==============================] - 1s 3ms/step - loss: 49632.1367 - mae: 49632.1367 - val_loss: 50270.4648 - val_mae: 50270.4648
Epoch 43/100
250/250 [==============================] - 1s 3ms/step - loss: 49624.2422 - mae: 49624.2422 - val_loss: 50266.6523 - val_mae: 50266.6523
Epoch 44/100
250/250 [==============================] - 1s 3ms/step - loss: 49614.8906 - mae: 49614.8906 - val_loss: 50259.6094 - val_mae: 50259.6094
Epoch 45/100
250/250 [==============================] - 1s 4ms/step - loss: 49599.9883 - mae: 49599.9883 - val_loss: 50257.0234 - val_mae: 50257.0234
Epoch 46/100
250/250 [==============================] - 1s 3ms/step - loss: 49590.0977 - mae: 49590.0977 - val_loss: 50254.1094 - val_mae: 50254.1094
Epoch 47/100
250/250 [==============================] - 1s 3ms/step - loss: 49580.0195 - mae: 49580.0195 - val_loss: 50249.1133 - val_mae: 50249.1133
Epoch 48/100
250/250 [==============================] - 1s 3ms/step - loss: 49573.3984 - mae: 49573.3984 - val_loss: 50246.1797 - val_mae: 50246.1797
Epoch 49/100
250/250 [==============================] - 1s 3ms/step - loss: 49565.9375 - mae: 49565.9375 - val_loss: 50245.2148 - val_mae: 50245.2148
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 49553.5625 - mae: 49553.5625 - val_loss: 50250.5938 - val_mae: 50250.5938
Epoch 51/100
250/250 [==============================] - 1s 3ms/step - loss: 49549.8633 - mae: 49549.8633 - val_loss: 50257.5312 - val_mae: 50257.5312
Epoch 52/100
250/250 [==============================] - 1s 3ms/step - loss: 49537.4727 - mae: 49537.4727 - val_loss: 50262.5859 - val_mae: 50262.5859
Epoch 53/100
250/250 [==============================] - 1s 3ms/step - loss: 49531.0000 - mae: 49531.0000 - val_loss: 50258.7578 - val_mae: 50258.7578
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 49522.6641 - mae: 49522.6641 - val_loss: 50246.4883 - val_mae: 50246.4883
Epoch 55/100
250/250 [==============================] - 1s 4ms/step - loss: 49518.1406 - mae: 49518.1406 - val_loss: 50255.5195 - val_mae: 50255.5195
Epoch 56/100
250/250 [==============================] - 1s 3ms/step - loss: 49508.4609 - mae: 49508.4609 - val_loss: 50249.9297 - val_mae: 50249.9297
Epoch 57/100
250/250 [==============================] - 1s 3ms/step - loss: 49503.1680 - mae: 49503.1680 - val_loss: 50249.8281 - val_mae: 50249.8281
Epoch 58/100
250/250 [==============================] - 1s 3ms/step - loss: 49496.4609 - mae: 49496.4609 - val_loss: 50247.8555 - val_mae: 50247.8555
Epoch 59/100
250/250 [==============================] - 1s 3ms/step - loss: 49490.8672 - mae: 49490.8672 - val_loss: 50254.0234 - val_mae: 50254.0234

In [78]:
%load_ext tensorboard

In [86]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 8400), started 0:00:52 ago. (Use '!kill 8400' to kill it.)

In [87]:
test_loss,test_mae=model.evaluate(x_test,y_test)
print(f'Test MAE: {test_mae}')

63/63 [==============================] - 0s 3ms/step - loss: 50245.2148 - mae: 50245.2148
Test MAE: 50245.21484375

In [89]:
model.save('regression_model.h5')

c:\Users\HP\OneDrive\Desktop\artificialnn\.venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(